### ISSUE TITLE
modrinth doesn't have the latest version

### ISSUE THREAD

**Issue by ryleu** [FakeDomi/ConnectedDoors#1]
your github version is updated to 1.19, but the modrinth page doesn't have that version

**Comment by FakeDomi** [comment]
That is correct. I'm only publishing to Github for now, but I'm considering making a small "mod hub" on my homepage in the future.

**Comment by ryleu** [comment]
i would really appreciate if you updated it, especially considering that tools like packwiz don't support arbitrary download links

**Comment by FakeDomi** [comment]
I don't want to put effort into uploading mods to a site where the moderators ban people cause they feel like it. 
That aside, Packwiz does appear to support external mods (https://packwiz.infra.link/tutorials/creating/adding-mods/) and I know that Modrinth packs also have Github releases whitelisted.

**Comment by JustAHuman-xD** [comment]
See something like aternos however doesnt support external mods

**Comment by JustAHuman-xD** [comment]
I understand if you dont want to update but it would be really nice if you could

**Comment by FakeDomi** [comment]
Sorry, it's not gonna happen from my side. The project's license is very permissive though, feel free to upload it to Modrinth yourself.

**Comment by ryleu** [comment]
> I don't want to put effort into uploading mods to a site where the moderators ban people cause they feel like it.

Makes sense. So far, Modrinth does not have any history of doing so (that I know of), but I get your reasoning. It would likely still be worthwhile for discoverability reasons.

> That aside, Packwiz does appear to support external mods (https://packwiz.infra.link/tutorials/creating/adding-mods/) and I know that Modrinth packs also have Github releases whitelisted.

I meant to say that it can't automatically update from GitHub releases, which is admittedly a minor inconvenience.
