### ISSUE TITLE
Fence Gate Support

### ISSUE THREAD

**Issue by BrandonItaly** [FakeDomi/ConnectedDoors#3]
I think Fence Gate support would be a nice addition to the mod

**Comment by FakeDomi** [comment]
Technically it would be possible, but do people actually build double fence gates?

**Comment by BrandonItaly** [comment]
Double fence gates are needed when moving entities with bigger hitboxes ¯\_(ツ)_/¯

**Comment by FakeDomi** [comment]
Added fence gate support in the latest version - unfortunately it's only compatible with 1.20 and above, let me know if you need it for an older version
