### ISSUE TITLE
add an on-off key

### ISSUE THREAD

**Issue by MrCookie112** [FakeDomi/ConnectedDoors#4]
Added an option to temporarily disable the mod in the event of incompatibility, for example with the "Private" plugin.

example of a problem where this option would be useful:

https://medal.tv/games/requested/clips/1wqBYjreWqqVp7/d1337ggkz5OX?invite=cr-MSxhMlIsMTk5MDM1MjI3LA

**Comment by FakeDomi** [comment]
I had already thought of a per-server blacklist before. Not sure if a hotkey is the correct solution for your case though. I assume the private plugin makes doors behave as connected server side?
Maybe checking for signs with special tokens would work best for this mod.

**Comment by FakeDomi** [comment]
I added a server blacklist in the config now. You can add either the name or the address to the respective list. If you put multiple, use semicolons ( ; ) as a separator.

**Comment by MrCookie112** [comment]
This plugin allows you to privatize doors and connect them when they are double doors. Personally, I'd prefer a button, as most of the doors on the server are not privatized. So I'd like to be able to use the mod on the server and disable it temporarily in problem situations.
