### ISSUE TITLE
Config doesn't work server-side

### ISSUE THREAD

**Issue by polymathom** [FakeDomi/ConnectedDoors#7]
I wanted to limit the effective distance for connected fence gates on my 1.21 server. The config file for Connected Doors did not appear in my server config file, so I uploaded a copy from my client. However, I found that the Connected Doors config does not function on the server side. A test confirmed that the config worked as intended on a single player world.

**Comment by FakeDomi** [comment]
The new version has a server side config.

**Comment by polymathom** [comment]
Fantastic! Thank you
